---

- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install python pip
      yum:
        name={{ item }}
        state=installed
      with_items:
        - python
        - python-pip

    - name: Install pip packages
      pip:
        name={{ item }}
        state=present
      with_items:
        - speedtest-cli
